name: Image

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      main-working-dir: "main"
      kind-working-dir: "kind"
      kind-git-ref: "9a2fea6909c44421b902661b21d054ccc1d54db7"
      IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/kind-eks-d"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ${{ env.main-working-dir }}

    - name: Checkout kind
      uses: actions/checkout@v2
      with:
        repository: kubernetes-sigs/kind
        path: ${{ env.kind-working-dir }}
        ref: ${{ env.kind-git-ref }}

    - name: Build kind
      run: sudo make install INSTALL_DIR=/usr/local/bin
      working-directory: ${{ env.kind-working-dir }}

    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: make build-image
      working-directory: ${{ env.main-working-dir }}

    - name: Pull image
      if: startsWith(github.ref, 'refs/tags/v')
      run: make pull-image
      working-directory: ${{ env.main-working-dir }}

    - name: Test image
      run: make test-image
      working-directory: ${{ env.main-working-dir }}

    - name: Push image
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: |
        make push-image
      working-directory: ${{ env.main-working-dir }}

    - name: Promote image
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        make promote-image GITHUB_REF=$GITHUB_REF
      working-directory: ${{ env.main-working-dir }}
