name: Image

on:
  push:
    branches:
      - "fork-master"
    tags:
      - "*"
  pull_request:
    branches:
      - fork-master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KIND_VERSION: "v0.11.1"
      IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/kind-eks-d"

    steps:
    - uses: styfle/cancel-workflow-action@0.9.0
      with:
        all_but_latest: true
        access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Get kind binary
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: ${{ env.KIND_VERSION }}
        skipClusterCreation: "true"

    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Download source
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: make update-src

    - name: Build image
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: make build-image

    - name: Pull image
      if: startsWith(github.ref, 'refs/tags/v')
      run: make pull-image

    - name: Test image
      run: make test-image

    - name: Push image
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: |
        make push-image

    - name: Promote image
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        make promote-image GITHUB_REF=$GITHUB_REF

