name: Image

on:
  push:
    branches:
      - "fork-master"
    tags:
      - "*"
  pull_request:
    branches:
      - fork-master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KIND_WORKING_DIR: "kind"
      KIND_GIT_REF: "9a2fea6909c44421b902661b21d054ccc1d54db7"
      IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/kind-eks-d"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout kind
      uses: actions/checkout@v2
      with:
        repository: kubernetes-sigs/kind
        path: ${{ env.KIND_WORKING_DIR }}
        ref: ${{ env.KIND_GIT_REF }}

    - name: Build and install kind
      run: sudo make install INSTALL_DIR=/usr/local/bin
      working-directory: ${{ env.KIND_WORKING_DIR }}

    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: make build-image

    - name: Pull image
      if: startsWith(github.ref, 'refs/tags/v')
      run: make pull-image

    - name: Test image
      run: make test-image

    - name: Push image
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: |
        make push-image

    - name: Promote image
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        make promote-image GITHUB_REF=$GITHUB_REF

