name: Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Get kind binary
      uses: engineerd/setup-kind@v0.5.0
      with:
        skipClusterCreation: "true"

    - name: Docker login
      run: |
        echo ${{ secrets.DOCKER_AUTH }} | docker login --username kbstci --password-stdin ghcr.io

    - name: Build image
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: make build-image

    - name: Pull image
      if: startsWith(github.ref, 'refs/tags/v')
      run: make pull-image

    - name: Test image
      run: make test-image

    - name: Push image
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: |
        make push-image

    - name: Promote image
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        make promote-image GITHUB_REF=$GITHUB_REF
